package com.example.sistemielektronikperkomunikiminestudenteve

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.View
import androidx.appcompat.app.AppCompatActivity
import com.example.sistemielektronikperkomunikiminestudenteve.databinding.FragmentDocumentsBinding
import com.example.sistemielektronikperkomunikiminestudenteve.databinding.FragmentFocusedPostBinding
import com.example.sistemielektronikperkomunikiminestudenteve.databinding.FragmentPostBinding

class focusedPost : Fragment(R.layout.fragment_focused_post) {


}